
.libPaths(c( "~/R_Commun/Adam/custom_lib/db-explorer/",.libPaths()))
# .libPaths(.libPaths()[1])
# unloadNamespace("nzsdse")
# unloadNamespace("dbplyr")
# unloadNamespace("radiant.data")
# unloadNamespace("plotly")
# unloadNamespace("broom")
# unloadNamespace("tidyr")
# unloadNamespace("dplyr")
# unloadNamespace("readr")
# unloadNamespace("shinyFiles")
# unloadNamespace("car")
# unloadNamespace("rio")
# unloadNamespace("haven")
# unloadNamespace("rio")
# unloadNamespace("patchwork")
# unloadNamespace("ggplot2")
# unloadNamespace("tibble")
# unloadNamespace("pillar")
# # unloadNamespace("arrow")
# unloadNamespace("vroom")
# unloadNamespace("tidyselect")
# unloadNamespace("pgsdse")
# unloadNamespace("orasdse")
# unloadNamespace("RJDBC")
# unloadNamespace("crayon")
# unloadNamespace("RPostgres")
# unloadNamespace("ROracle")
# unloadNamespace("RSQLite")
# unloadNamespace("DBI")
# unloadNamespace("stringr")
# unloadNamespace("usethis")
# unloadNamespace("forcats")
# unloadNamespace("scales")
# unloadNamespace("gtable")
# unloadNamespace("glue")


library(crayon)
library(shinyAce)
library(shiny)
library(shinyhelper)
library(glue)
# library(bslib)
library(dplyr)
library(DBI)
library(dbplyr)
library(purrr)
library(rlang)
library(orasdse)
library(pgsdse)
library(nzsdse)
library(fontawesome)
library(stringi)
library(stringr)
library(sodium)
# library(rclipboard)

options(java.parameters = c("-XX:+UseConcMarkSweepGC", "-Xmx8192m","-Xss3m"))

