library(magrittr)
library(crayon)
library(shinyAce)
library(shiny)
library(glue)
library(dplyr)
library(DBI)
library(dbplyr)
library(purrr)
library(rlang)
library(fontawesome)
library(stringr)
library(shinyjs)
library(shinyBS)

# library(DT)
# library(fan)
# library(tidyr)
# library(rmarkdown)
# library(stringi)
# library(data.table)
# library(htmltools)
# library(shinyWidgets)
# library(withr)

options(java.parameters = c("-XX:+UseConcMarkSweepGC", "-Xmx8192m","-Xss3m"))
